### PR TITLE
Wrapped `CallNonvirtual*Method`

### PR DESCRIPTION
**Pull request by Rabbit0w0**
## Overview

Added function `call_nonvirtual_method(_unchecked)`

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by [automated tests](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has documentation
- [x] User-visible changes are mentioned in the Changelog
- [x] The continuous integration build passes

### CODE REVIEW

**Comment by rib** [comment]
Thanks for looking at this!

This addition looks good to me and it's a bit surprising that it wasn't added before.

It would be great if you'd be able to add a unit test for the new API and add a changelog entry.

**Comment by Rabbit0w0** [comment]
Sorry but I still don't know how to add unit tests without extra testing classes to be added into JVM.

**Comment by rib** [comment]
Can we find something in `java.lang` perhaps that we can do a minimal test with?

**Comment by Rabbit0w0** [comment]
Okay now.

**Review by rib — APPROVED** [review]

**Comment by rib** [comment]
Perfect, thanks for this!

**Pull request merged**
