### PR TITLE
Bump the version to 0.18.0.

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
Bump the version to 0.18.0.

### CODE REVIEW

**Comment by aleksuss** [comment]
Take a look please at this PR #259 before bump version.

**Review by stanislav-tkach — APPROVED** [review]
LGTM, but I also think that #259 should be merged first.

**Comment by dmitry-timofeev** [comment]
Makes sense, let's delay till that fix is integrated, and till we sort out whether any extensions to errors are needed.

**Comment by maxv-rust** [comment]
Could you please take a look at https://github.com/jni-rs/jni-rs/pull/266? Is it too late for new functionality to be merged?

**Comment by dmitry-timofeev** [comment]
> Could you please take a look at #266? Is it too late for new functionality to be merged?

I suggest we make a separate release with WeakGlobalRef, as there are some open questions in #266.

**Pull request merged**
