### PR TITLE
Add Send and Sync implementations for JMethodID

### PR DESCRIPTION
**Pull request by stanislav-tkach**
### Definition of Done

- [x] There are no TODOs left in the code
- [ ] Change is covered by [automated tests](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has documentation
- [x] User-visible changes are mentioned in the Changelog
- [ ] The continuous integration build passes

### CODE REVIEW

**Review by dmitry-timofeev — COMMENTED** [review]
1. There was also a consideration on too restrictive lifetimes (also in #38)
2. There are also JFieldIDs, which are the same.

**Review by dmitry-timofeev — COMMENTED** [review]
There are also JStatic*IDs :)

**Comment by dmitry-timofeev** [comment]
> There was also a consideration on too restrictive lifetimes (also in #38) 

Also, doesn't it make sense to extend the lifetimes? My understanding is that with such lifetimes it's not really easy to share them between threads.

**Comment by stanislav-tkach** [comment]
> There was also a consideration on too restrictive lifetimes (also in #38)

I'm not sure how to correctly handle the lifetimes and preserve the ergonomics. As far as I can see, the lifetime should be bound to a class, so the the following definition is incorrect:
```rust
pub fn get_field_id<'c, T, U, V>(&self, class: T, name: U, sig: V) -> Result<JFieldID<'a>>
    where
        T: Desc<'a, JClass<'c>>,
        U: Into<JNIString>,
        V: Into<JNIString>,
    {
        // Now we have a class, but its lifetime is limited to this function, 
        // so `JFieldID` cannot outlive it either.
        let class = class.lookup(self)?;

        ...
```

The signature can be changed to the following:
```rust
pub fn get_field_id<'c, T, U, V>(&self, class: JClass<'c>, name: U, sig: V) -> Result<JFieldID<'c>>
    where
        U: Into<JNIString>,
        V: Into<JNIString>,
```
But in this case getting a field id would be more verbose:
```rust
// Current api:
let field_id = env.get_field_id("com/my/Class", "intField", "I");

// New api:
let class = "com/my/Class".lookup()?;
let field_id = env.get_field_id(class, "intField", "I");
```
Additionally, I'm not sure that this solves all lifetime issues:
```rust
let global_class;
let field_id;
{
    let class = "com/my/Class".lookup()?;
    field_id = env.get_field_id(class, "intField", "I");

    // Keep the class alive with a GlobalRef:
    global_class = new_global_ref(class)?;
}
// Here `class` goes out of scope, so Rust will complain about the `field_id` lifetime, 
// because it knows nothing about the class to global_class relation.
```
I don't see a clear solution here. Am I missing something?

**Comment by dmitry-timofeev** [comment]
> As far as I can see, the lifetime should be bound to a class

Yes, the lifetime should be bound to a Java class. However, for the avoidance of doubt, it does not necessarily have to be bound to the class _native reference_ used to look up the method ID. The method ID won't go away just because a class native reference has been deleted; it will only go away if the class gets unloaded. Keeping any _native reference_ to the class object (`Class` instance) or to any instance of that class is enough to guarantee the method/field ID remains valid.

To prevent any possible window when the class can be unloaded, probably it's best to keep the same class _native reference_ that was used to create an ID.

Possibly, one solution is to marry IDs with class references, so that you can't keep an ID without a class reference. Would it require different types for global and local class refs?

The questions seem to be:
- How much safety are we willing to provide?
- If it is right to restrict sharing of these IDs across threads (allowed by the spec _if_ the class is kept alive — but that's the developer's responsibility) just because we can't guarantee safety?

Answers to that might help choose between:
- Keep as is (no Sync, no Send). Users have to fallback to unsafe to share across threads.
- Allow sharing, do not put safety measures. Keeping the class alive is on the user.
- Implement (class_ref + id) pairs, making unsafe usage impossible. Might need x2 types, to accomodate local and global class refs (local for cases when you keep IDs in a single JNIEnv context).

**Comment by stanislav-tkach** [comment]
I need to think a little bit more about this, but right now I'm more inclined to the third approach (save class_ref + id pairs).

**Pull request closed without merging**
