### PR TITLE
Update dynamic library path enviroment variable on macOS for test.

### PR DESCRIPTION
**Pull request by xianminx**
## Overview

According to https://doc.rust-lang.org/cargo/reference/environment-variables.html#dynamic-library-paths
macOS use `DYLD_FALLBACK_LIBRARY_PATH` instead of `LD_LIBRARY_PATH` to locate dynamic libraries.

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by [automated tests](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has documentation
- [x] User-visible changes are mentioned in the Changelog
- [ ] The continuous integration build passes

### CODE REVIEW

**Review by stanislav-tkach — APPROVED** [review]
Should there also be `PATH` for Windows?..

**Comment by xianminx** [comment]
> Should there also be `PATH` for Windows?..

According to the document, should there be, but I have no Windows to test against. I will add `PATH` to `test_profile` and then checkout the CI results to see if it works as expected. Currently, `cargo run test` just ignores invocation tests on my local macOS if I do not set `DYLD_FALLBACK_LIBRARY_PATH ` correctly. 

But I am curious why Github CI `DO` run all invocation tests on macOS and Windows successfully, 
https://github.com/jni-rs/jni-rs/runs/6811578948?check_suite_focus=true

**Comment by dmitry-timofeev** [comment]
It is a bash script, so I don't think it has to have anything for Windows.

**Review by dmitry-timofeev — APPROVED** [review]

**Comment by xianminx** [comment]
@dmitry-timofeev  It seems I do not have permission to trigger re-check. Could you help re-run the check so this PR can be merged. Thanks a lot.

**Pull request merged**
