### PR TITLE
Call into libjli.dylib instead of libjvm.dylib for MacOS

### LINKED ISSUE #220: `System.loadLibrary` failed on MacOS when jvm created with invocation API
Steps to reproduce:
1. Create jvm with `JavaVM::new(args)`
2. Run some java code that will load native library.
3. If there is no jdk in your system whose plist have:
```
      <key>JVMCapabilities</key>
      <array>
        <string>CommandLine</string>
        <string>JNI</string>
      </array>
```
you will see 
image
and program will terminated.

Proposed solution:
According to https://bugs.openjdk.java.net/browse/JDK-8064542 `JNI_CreateJavaVM` should be called from libjli.dylib. My experiments also show that it works fine.

### LINKED ISSUE #229: “No Java runtime present, requesting install.” message on MacOS High Sierra
On MacOS High Sierra I'm seeing the dialog “No Java runtime present, requesting install.” when my rust executable is calling the JavaVM invocation API, and subsequently immediately terminates. I've also made sure both `JAVA_HOME` and `LD_LIBRARY_PATH` are set correctly to the installed JDK on the MacOS machine. 

I'm using JDK version 1.8.0. 

After doing some searching, it seems like I'm not the only one experiencing this issue.
- https://github.com/xamarin/java.interop/pull/198
- https://github.com/JuliaInterop/JavaCall.jl/issues/100 
- https://github.com/kivy/pyjnius/pull/441
- https://github.com/imagej/pyimagej/issues/10

It seems like the workaround to the issue is to link to `libjli.dylib` instead of `libjvm.dylib` on MacOS. 

I've locally modified `build.rs` to test this out, and can confirm that this workaround does fix the issue.

### PR DESCRIPTION
**Pull request by tiepettersen**
## Overview

This is a workaround for the legacy Java SE6 popup on MacOS.

If you don't have the legacy Java6 installed then the call to
`JNI_CreateJavaVM()` will result in a popup requesting you to install it
and abort, even if you call the `libjvm.dylib` that's included as part of
JDK8.

According to jpype-project/jpype#160 and
https://bugs.openjdk.java.net/browse/JDK-7131356 this is a Java8 bug and
the recommended fix is to call into `libjli.dylib` instead.

This PR fixes #220 and fixes #229. 

### See Also

- https://bugs.openjdk.java.net/browse/JDK-8064542?focusedCommentId=13624328&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13624328 
- https://bugs.openjdk.java.net/browse/JDK-7131356

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by automated [tests](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has documentation
- [x] This change is not breaking **or** mentioned in the Changelog
- [x] The [continuous integration build](https://www.travis-ci.org/jni-rs/jni-rs) passes

### CODE REVIEW

**Comment by tiepettersen** [comment]
It seems like beta build fails on travis due to a clippy error on some unrelated jni code.

**Comment by DarkEld3r** [comment]
Clippy should be fixed with this pull request: https://github.com/jni-rs/jni-rs/pull/231

**Comment by tiepettersen** [comment]
@DarkEld3r, @dmitry-timofeev, one of you need to merge, I don't have write access :)

**Comment by dmitry-timofeev** [comment]
It's in, thanks!

**Comment by dmitry-timofeev** [comment]
> It seems like beta build fails on travis due to a clippy error on some unrelated jni code.

Configured weekly cron builds on Travis CI to check for that.

**Pull request merged**
